<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-BMTHO9F" ignored="6" name="Test" tests="2" failures="1" timestamp="22 Aug 2018 06:11:18 GMT" time="14.011" errors="0">
  <testcase name="validSettingsSave" time="1.848" classname="tests.AccountTests"/>
  <testcase name="invalidSettingsSave" time="0.89" classname="tests.AccountTests">
    <failure type="java.lang.AssertionError" message="expected [An error has occurred! Settings could not be saved.] but found []">
      <![CDATA[java.lang.AssertionError: expected [An error has occurred! Settings could not be saved.] but found []
	at tests.AccountTests.invalidSettingsSave(AccountTests.java:38)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- invalidSettingsSave -->
  <testcase name="validLogin" time="0.0" classname="tests.LoginTests">
    <ignored/>
  </testcase> <!-- validLogin -->
  <testcase name="invalidLogin" time="0.0" classname="tests.LoginTests">
    <ignored/>
  </testcase> <!-- invalidLogin -->
  <testcase name="deleteBranch" time="0.0" classname="tests.BranchTests">
    <ignored/>
  </testcase> <!-- deleteBranch -->
  <testcase name="createValidBranch" time="0.0" classname="tests.BranchTests">
    <ignored/>
  </testcase> <!-- createValidBranch -->
  <testcase name="invalidRegisterUser" time="0.0" classname="tests.LoginTests">
    <ignored/>
  </testcase> <!-- invalidRegisterUser -->
  <testcase name="editBranch" time="0.0" classname="tests.BranchTests">
    <ignored/>
  </testcase> <!-- editBranch -->
</testsuite> <!-- Test -->
